// <auto-generated />
namespace AFSport.Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IsAtivoemtodastabelas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsAtivoemtodastabelas));
        
        string IMigrationMetadata.Id
        {
            get { return "201805010535141_IsAtivo em todas tabelas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
